[package]
name = "ic-ledger-canister-core"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
async-trait = "0.1.53"
candid = "0.8.1"
ic-base-types = { path = "../../types/base_types" }
ic-constants = { path = "../../constants" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-canister-log = { path = "../../rust_canisters/canister_log" }
ic-ledger-core = { path = "../ledger_core" }
ic-utils = { path = "../../utils" }
ic-ledger-hash-of = { path = "../../../packages/ic-ledger-hash-of" }
num-traits = "0.2.12"
serde = "1.0"
