[package]
name = "ic-bitcoin-canister-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
bech32 = "0.9.0"
candid = { workspace = true }
ic-btc-interface = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-ckbtc-minter = { path = "../ckbtc/minter" }
rand = "0.8.5"
serde = "1.0.130"
serde_bytes = "0.11"

[dev-dependencies]
bitcoin = "0.28.1"
ic-base-types = { path = "../../types/base_types" }
ic-config = { path = "../../config" }
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../test_utilities/load_wasm" }
ic-universal-canister = { path = "../../universal_canister/lib" }
hex = "0.4.3"
