[package]
name = "ic-icrc1-client"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "ICRC-1 compliant client library."
edition = "2021"

[dependencies]
async-trait = "0.1.53"
candid = { workspace = true }
ic-base-types = { path = "../../../types/base_types" }
ic-icrc1 = { path = "../" }
ic-ledger-core = { path = "../../ledger_core" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
num-traits = "0.2.14"
serde = "1.0"
