[package]
name = "ic-cketh-minter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-cketh-minter"
path = "src/main.rs"

[dependencies]
candid = { workspace = true }
ciborium = { workspace = true }
ethabi = "18.0.0"
ethnum = { workspace = true }
hex = "0.4"
ic-ic00-types = { path = "../../../types/ic00_types" }
hex-literal = "0.4.1"
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-crypto-ecdsa-secp256k1 = { path = "../../../crypto/ecdsa_secp256k1" }
ic-crypto-sha3 = { path = "../../../crypto/sha3" }
ic-metrics-encoder = "1"
rlp = "0.5.2"
num-bigint = "0.4.3"
serde = "1"
serde_json = "1"
serde_bytes = "0.11"

[dev-dependencies]
ethers-core = "2.0.8"
assert_matches = "1.5.0"
