[package]
name = "ic-boundary"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-boundary"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
arc-swap = "1"
async-scoped = { version = "0.7", features = ["use-tokio"] }
async-trait = "0.1.56"
axum = "0.6.1"
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
bytes = "1.4.0"
candid = "0.8.4"
clap = { version = "4", features = ["derive"] }
ethnum = "1.3.2"
futures = "0.3.21"
futures-util = "0.3.28"
hex = "0.4.3"
hyper = "0.14.18"
hyper-rustls = "0.24.0"
ic-config = { path = "../../config" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
ic-logger = { path = "../../monitoring/logger" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../../registry/client" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-local-store = { path = "../../registry/local_store" }
ic-registry-replicator = { path = "../../orchestrator/registry_replicator" }
ic-types = { path = "../../types/types" }
instant-acme = "0.3.2"
lazy_static = "1.4.0"
mockall = "0.11.4"
prometheus = "0.13"
rcgen = "0.10.0"
# same feature as in bazel
reqwest = { version = "0.11.18", features = [ "blocking", "json", "multipart", "native-tls", "rustls-tls", "stream"] }
rustls = { version = "0.21.2", features = ["dangerous_configuration"] }
serde = "1.0.163"
serde_cbor = "0.11.2"
serde_json = "1.0.96"
slog = "2.5.2"
tempfile = "3.6.0"
thiserror = "1.0.40"
tokio = { version = "1.19.2", features = ["full"] }
tokio-rustls = { version = "0.24.0", features = ["dangerous_configuration"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["json"] }
url = "2.1.1"
x509-parser = { version = "0.15.0", features = ["verify"] }

[dev-dependencies]
wiremock = "=0.5.18"
ic-crypto-test-utils-keys = { path ="../../crypto/test_utils/keys" }
ic-registry-client-fake = { path = "../../registry/fake" }
ic-registry-proto-data-provider = { path = "../../registry/proto_data_provider" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-registry = { path = "../../test_utilities/registry" }
