devcontainer-build:
  extends:
    - .ubuntu-cargo-k8s
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - .devcontainer/*
  needs: []
  script:
    - |
      set -euo pipefail

      # shellcheck disable=SC1091
      source /opt/nvm/nvm.sh
      devcontainer build . --image-name ic-devenv
