cargo-clippy-linux:
  needs: []  # don't wait on other jobs
  extends:
    - .bazel-build-k8s
    - .bazel-rules-pipeline
  tags:
    - dfinity-ic # overwritting so we do not inherit the zh tag
  variables:
    CARGO_BUILD_TARGET: "x86_64-unknown-linux-gnu"
  script:
    - |
      set -eExuo pipefail
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" build-command -- \
          "$CI_PROJECT_DIR"/gitlab-ci/src/rust_lint/lint.sh

# Cargo is deprecated and will be replaced with Bazel.
# Until the migration is complete, run a simple check for build failures.
legacy-cargo-check:
  needs: []  # don't wait on other jobs
  extends:
    - .bazel-build-k8s
    - .bazel-rules-pipeline
  tags:
    - dfinity-ic # overwritting so we do not inherit the zh tag
  script:
    - |
      set -eExuo pipefail
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" build-command -- cargo check --tests --benches

cargo-build-release-linux:
  needs: []  # don't wait on other jobs
  extends:
    - .bazel-build-k8s
    - .bazel-rules-pipeline
  tags:
    - dfinity-ic # overwritting so we do not inherit the zh tag
  script:
    - |
      set -eExuo pipefail
      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" build-command -- cargo build --release
