.build-determinism-release:
  extends:
    - .ubuntu-k8s
    - .rules-scheduled-reproducibility
  needs:
    - job: build-ic-release
  script:
    - |
      set -eExuo pipefail

      # TODO IDX-2757
      if [ "$CI_JOB_NAME" == "build-determinism-guest-update-img-release" ]; then
          OLD_PATH="$(git rev-parse HEAD)/build-ic-release/guest-os/update-img"
          if curl -sfSI --retry 2 "https://download.dfinity.systems/ic/$OLD_PATH/SHA256SUMS"; then
              PATH0="build-ic-release/guest-os/update-img"
          fi
      fi

      # what we've build in build-ic-release
      P0=$PATH0
      # what is live and available under $NNS_RELEASE_VERSION
      # NNS_RELEASE_VERSION is set in build-ic-release
      # shellcheck disable=SC2153
      P1="/${NNS_RELEASE_VERSION}/${PATH1}"

      ./gitlab-ci/tools/build-diff.sh "$P0" "$P1"

build-determinism-binaries-release:
  extends:
    - .build-determinism-release
  parallel:
    matrix:
      - PATH0: "build-ic-release/release"
        PATH1: "release"
      - PATH0: "build-ic-release/canisters"
        PATH1: "canisters"
      - PATH0: "build-ic-release/guest-os"
        PATH1: "guest-os/update-img"
