[package]
name = "ic-crypto-standalone-sig-verifier"
version = "0.8.0"
edition = "2021"
description = "Standalone crypto library to verify cryptographic signatures for the Internet Computer"

[dependencies]
ic-crypto-iccsa = { path = "../iccsa" }
ic-crypto-internal-csp = { path = "../internal/crypto_service_provider" }
ic-crypto-internal-basic-sig-ecdsa-secp256k1 = { path = "../internal/crypto_lib/basic_sig/ecdsa_secp256k1" }
ic-crypto-internal-basic-sig-ecdsa-secp256r1 = { path = "../internal/crypto_lib/basic_sig/ecdsa_secp256r1" }
ic-crypto-internal-basic-sig-ed25519 = { path = "../internal/crypto_lib/basic_sig/ed25519" }
ic-crypto-internal-basic-sig-rsa-pkcs1 = { path = "../internal/crypto_lib/basic_sig/rsa_pkcs1" }
ic-crypto-sha2 = { path = "../sha2" }
ic-types = { path = "../../types/types" }

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4.3"
ic-crypto-internal-test-vectors = { path = "../internal/test_vectors" }
ic-crypto-test-utils-canister-sigs = { path = "../test_utils/canister_sigs" }
ic-crypto-test-utils-reproducible-rng = { path = "../test_utils/reproducible_rng" }
strum = "0.23.0"
