[package]
name = "ic-btc-types-internal"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-btc-interface = { workspace = true }
ic-protobuf = { path = "../../../protobuf" }
serde = "1.0.132"
serde_bytes = "0.11"
