[package]
name = "ic-icrc1-index-ng"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "Index canister for the ICRC1 Ledger"
edition = "2018"

[[bin]]
name = "ic-icrc1-index-ng"
path = "src/main.rs"

[dependencies]
candid = "0.8.1"
ciborium = "0.2"
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-cdk = { version = "0.6.0" }
ic-cdk-macros = { version = "0.6.0" }
ic-cdk-timers = "0.1.2"
ic-crypto-sha = { path = "../../../crypto/sha" }
ic-icrc1 = { path = "../" }
ic-ledger-core = { path = "../../ledger_core" }
ic-metrics-encoder = "1.1"
ic-stable-structures = "0.5.3"
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
num-traits = "0.2.14"
scopeguard = "1.1.0"
serde = "1.0"

[dev-dependencies]
ic-base-types = { path = "../../../types/base_types" }
ic-icrc1-index = { path = "../index" }
ic-icrc1-ledger = { path = "../ledger" }
ic-icrc1-test-utils = { path = "../test_utils" }
ic-ledger-canister-core = { path = "../../ledger_canister_core" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
proptest = "1.0"