[package]
name = "ic-crypto-tree-hash-fuzz-check-witness-equality-utils"
version = "0.8.0"
publish = false
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
ic-canonical-state = { path = "../../../../canonical_state" }
ic-crypto-test-utils-reproducible-rng = { path = "../../../test_utils/reproducible_rng" }
ic-crypto-tree-hash = { path = "../.." }
ic-crypto-tree-hash-test-utils = { path = "../test_utils" }
