---
- hosts: localhost
  any_errors_fatal: yes
  gather_facts: false
  become: false

  tasks:
    - name: Remove all Prometheus scraping targets
      vars:
        ic: "{{ ic_deployment_name }}"
      uri:
        url: "https://{{ service_discovery_server }}/service-discovery/{{ ic }}"
        method: DELETE
        return_content: true
        validate_certs: no
      register: delete_response
      failed_when: delete_response.status not in [200, 400]
