[package]
name = "stable_memory_integrity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.5.0"
candid = { workspace = true }
canister-test = { path = "../canister_test" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-types = { path = "../../types/types" }
lazy-static = "1.4.0"
serde = "1.0.136"
proptest = "1.2.0"

[[bin]]
name = "stable_memory_integrity"
path = "bin/main.rs"
