[package]
name = "ic-nervous-system-runtime"
version = "0.0.1"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
async-trait = "0.1.57"
candid = { workspace = true }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-base-types = { path = "../../types/base_types" }
ic-cdk = { workspace = true }
