[package]
name = "certificate_orchestrator_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
addr = { version = "0.15.6", default-features = false, features = ["idna"] }
candid = { workspace = true }
ic-stable-structures = { workspace = true }
serde = "1.0.148"
serde_bytes = "0.11.7"
thiserror = "1.0.37"
