[package]
name = "ic-canister-serve"
version = "0.1.0"
edition = "2021"
authors = ["The Internet Computer Project Developers"]
description = "A library for serving assets over the http_endpoint of smart contracts running on the Internet Computer."
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ic-canister-serve"
keywords = ["internet-computer", "dfinity", "canister"]
repository = "https://github.com/dfinity/ic"
include = ["src", "Cargo.toml", "LICENSE", "README.md"]

[dependencies]
by_address = "1.1.0"
ic-canister-log = { path = "../canister_log", version = "0.2.0" }
ic-cdk = "0.7.4"
ic-metrics-encoder = "1.1.0"
maplit = "1.0.2"
priority-queue = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"