[package]
name = "ic-ckbtc-agent"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
description = "Agent for the ckBTC minter."
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-agent = { workspace = true }
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-ckbtc-minter = { path = "../minter" }
ic-icrc1 = { path = "../../../rosetta-api/icrc1" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
num-traits = "0.2.15"
